name: CMake Windows Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: ${{ matrix.preset }}
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        preset: [ "Debug", "Release", "RelWithDebInfo", "MinSizeRel" ]

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Configure
      run: cmake -B build --preset ${{ matrix.preset }}

    - name: Build
      run: cmake --build build --preset ${{ matrix.preset }}
