name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

defaults:
  run:
    shell: bash

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        config:
          - { name: Debug, build_type: Debug }
          - { name: Release, build_type: Release }
          - { name: RelWithDebInfo, build_type: RelWithDebInfo }
          - { name: MinSizeRel, build_type: MinSizeRel }

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Configure
      run: cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.config.build_type }}

    - name: Build
      run: cmake --build build --config ${{ matrix.config.build_type }}
